### ISSUE TITLE
Feature request: show RFC9234 "Only To Customer" (OTC) attribute

### ISSUE THREAD

**Issue by pierky** [NLNOG/lg.ring.nlnog.net#102]
It'd be great if the LG could show the presence of the OTC attribute from https://datatracker.ietf.org/doc/rfc9234/

Some routes having that attribute have been documented in https://rfc.hashnode.dev/rfc9234-observed-in-the-wild recently.

**Comment by teunvink** [comment]
Sounds like a nice idea, thanks for the suggestion. The LG backend has this information, I'll have to read a bit more on how this attributes are used but I think we can add them to our LG quite easily.

**Comment by teunvink** [comment]
Fixed, OTC is now shown in the output, as can be seen for example here: https://lg.ring.nlnog.net/prefix?saved=StbTR1dOvA
