### ISSUE TITLE
community text list

### ISSUE THREAD

**Issue by teunvink** [NLNOG/lg.ring.nlnog.net#33]
create a page showing all asn's for which communities are known (and possibly all known communities for these asns).

**Comment by BrendanHalley** [comment]
Hey,

Did the communities.html file get missed from your commit or does it still need to be created?

**Comment by teunvink** [comment]
I actually forgot to add it to the commit, thanks!

**Comment by BrendanHalley** [comment]
Looks good! Just wanted to check before I created it 😄
