### ISSUE TITLE
Fill in wildcard values in community names

### ISSUE THREAD

**Issue by teunvink** [NLNOG/lg.ring.nlnog.net#53]
If wildcard values are used in a community description rules, it would be nice to be able to fill in the actual value. For example:

If `65535:0:nnn,do not announce to $1` matches `65535:0:12345`, the description could be `do not announce to 12345`. Exact notation could be different.

**Comment by job** [comment]
Supporting backreferences is a nice idea

**Comment by teunvink** [comment]
This works now, not real backrefs, but we can use matches in the regexp on the community part as values in the description part. Matches are indexed:

```
65500:666:nnn,do not announce to AS$0
65500:nnn:nnn,prepend $0 times to AS$1
```
