### ISSUE TITLE
PeeringDB looking glass URL support

### ISSUE THREAD

**Issue by wouterprins** [NLNOG/lg.ring.nlnog.net#75]
It would be great to be able to add a looking glass URL in peeringdb that points to a specific peer on the NLNOG looking glass interface.

**Comment by teunvink** [comment]
We should combine this with a generic option to choose a set of peers to do the query on. Not hard to do, except for the bootstrap/HTML stuff which I'm fighting with now. I want to have a dropdown selectbox with multiple options (so maybe checkboxes or something similar). Haven't found anything yet that works nicely with bootstrap 5, only older stuff.

**Comment by teunvink** [comment]
This has been implemented, you can now use URLs like this: 

https://lg.ring.nlnog.net/?peer=BIT1-v4&peer=BIT1-v6
