### ISSUE TITLE
bgpmap doesn't colour nodes, only edges

### ISSUE THREAD

**Issue by athompson-merlin** [NLNOG/lg.ring.nlnog.net#82]
If we look at e.g. https://lg.ring.nlnog.net/prefix/map/fullscreen?saved=NzJt5I4hXA, we see that the edges are coloured, but not the nodes.  This can make it quite difficult to follow a path, at least under some circumstances.
I just found the source of this problem in bird-lg-go, and it looks like this codebase inherits the same root cause (no big surprise there!).
Instead of duplicating it all again, I'll just refer to that issue here: https://github.com/xddxdd/bird-lg-go/issues/66

In a perfect world, I would be able to toggle this on and off, but at least for my purposes/my monitor/my printer/my eyes, I think coloured nodes AND edges would be an improvement over black nodes and coloured edges.

**Comment by athompson-merlin** [comment]
While I'm wishing, it would be really nice if I could download the DOT source from the LG, as I have lots of tools for manipulating DOT graphs locally, whereas I can't really do anything interesting or useful with the laid-out & rendered SVG output.

**Comment by teunvink** [comment]
I can take a look at this, but don't see this as a top priority, and only acceptable if the default is no colored edges. We have an option to store preferences, so a toggle is doable. I moved the request for downloading dotfiles to a new issue (#83).

**Comment by athompson-merlin** [comment]
If I care REALLY strongly about it, I'll figure out how to fix the code and provide the patch.  Otherwise, it's a common mis-feature (IMHO) in all the codebases derived from bird-lg so I'm providing background info on what the root cause is, and what the fix is.  YMMV, obviously.  Otherwise this is one of the most featureful and pleasant LGs to use,  so much so that I know a few people (including myself) who are going to try using it for themselves.

**Comment by teunvink** [comment]
Node coloring has been added.
