### ISSUE TITLE
download dot source for LG map

### ISSUE THREAD

**Issue by teunvink** [NLNOG/lg.ring.nlnog.net#83]
While I'm wishing, it would be really nice if I could download the DOT source from the LG, as I have lots of tools for manipulating DOT graphs locally, whereas I can't really do anything interesting or useful with the laid-out & rendered SVG output.

_Originally posted by @athompson-merlin in https://github.com/NLNOG/lg.ring.nlnog.net/issues/82#issuecomment-1334575181_

**Comment by teunvink** [comment]
Fixed, there's a download button now on the map page.

**Comment by athompson-merlin** [comment]
Awesome, thanks!
