### ISSUE TITLE
bgp map readibility issue

### ISSUE THREAD

**Issue by andrewnyr** [NLNOG/lg.ring.nlnog.net#94]
Sometimes on the BGP map, bubbles will have a black bubble with black text making the text impossible to read.

![chrome_kyh55lH3Hd](https://user-images.githubusercontent.com/47006659/212016588-4e58237b-451d-49e9-b036-16399ed6fe87.jpg)

**Comment by teunvink** [comment]
This should be fixed now.

**Comment by andrewnyr** [comment]
@teunvink it seems this issue has returned :(

<img width="1128" alt="chrome_d1IxBimmxD" src="https://user-images.githubusercontent.com/47006659/226513843-4232f35f-b92c-4811-93bc-dcd7ee477095.png">

**Comment by teunvink** [comment]
It didn't return, it was just one specific case that wasn't properly handled. It's fixed now.
